PADV-501: Add LTI 1.3 external configuration fields
Pearson-Advance/openedx-ltistore pull request #1
Opened 2023-05-18 06:06 UTC by kuipumu

## Ticket

https://agile-jira.pearson.com/browse/PADV-501

## Description

This PR adds LTI 1.3 fields to the external configuration model.

## Type of Change

- [x] Add LTI 1.3 fields to external configuration model.
- [x] Add model clean method to validate LTI 1.1/1.3 fields.
- [x] Add model save method to generate missing LTI 1.3 fields and generate JWK.
- [x] Add external configuration model unit tests.

## Testing:

- Run the LMS: `make dev.up.lms`.
- Install `openedx-ltistore` on the LMS.
- Go to LMS > Admin > LTI_STORE > External lti configurations.
- Add a new external LTI configuration.

## Reviewers

- [ ] @Squirrel18 
- [ ] @anfbermudezme

2023-05-24 16:07 UTC, Squirrel18 requested changes

2023-05-24 16:14 UTC, kuipumu commented on lti_store/models.py
> +    lti_1p3_private_key = models.TextField(
@Squirrel18 The lti_1p3_private_key field cannot be shared across configurations, each configuration has is own private key, ¿or are you referring to something else?

2023-05-24 16:16 UTC, kuipumu commented on lti_store/models.py
> +                        "lti_1p3_tool_public_key": _(
@Squirrel18 Because the valitation error is related to both fields

2023-05-25 15:12 UTC, anfbermudezme commented on lti_store/tests/test_models.py
> +                }
Trailing comma.

2023-05-25 15:12 UTC, anfbermudezme commented on lti_store/tests/test_models.py
> +                }
Trailing comma.

2023-05-25 15:12 UTC, anfbermudezme commented on lti_store/tests/test_models.py
> +                }
Trailing comma.

2023-05-25 15:12 UTC, anfbermudezme commented on lti_store/tests/test_models.py
> +            self.PRIVATE_KEY, config.lti_1p3_private_key_id
Trailing comma.

2023-05-25 15:12 UTC, anfbermudezme commented on lti_store/models.py
> +    lti_1p3_client_id = models.CharField(
Is the intention of defining these configurations to act as serializers?

2023-05-25 15:12 UTC, anfbermudezme commented on lti_store/models.py
> +def validate_private_key(value):
```suggestion
def validate_private_key(key):
```

2023-05-25 18:33 UTC, kuipumu commented on requirements/base.txt
> +django==3.2.19
@anfbermudezme pip-compile upgraded Django because openedx-filter==1.2.0, there is no mayor difference from previous Django version so I preferred to left the compiled file unchanged

2023-05-25 18:35 UTC, kuipumu commented on lti_store/models.py
> +    lti_1p3_client_id = models.CharField(
@anfbermudezme No, these values will be queried using openedx-filters by xblock-lti-consumer

2023-05-26 15:19 UTC, Squirrel18 requested changes

2023-05-26 15:54 UTC, Squirrel18 approved these changes

2023-05-26 16:35 UTC, anfbermudezme approved these changes

2023-05-26 16:45 UTC, merged