PADV-502: Add LTI 1.3 access token endpoint
Pearson-Advance/openedx-ltistore pull request #2
Opened 2023-06-01 01:52 UTC by kuipumu

## Ticket

https://agile-jira.pearson.com/browse/PADV-502

## Description

This PR adds LTI 1.3 access token endpoint to the plugin views. This endpoint is used by LTI tools to request accesss tokens that they can use to interact with the LTI advantage services (AGS, NPRS) on the LTI platform

## Type of Change

- [x] Add test requirements.
- [x] Add access_token_endpoint view.
- [x] Add URLS configuration.
- [x] Add ToolKeyHandler and PlatformKeyHandler classes.
- [x] Add get_lti_api_base utility.
- [x] Add LTI 1.3 exception classes.
- [x] Add test for views, urls and utils modules.
- [x] Update plugin_app url_config.
- [x] Update test settings ROOT_URLCONF value.
- [x] Update test requirements to match base requirements

## Testing:

- Run the LMS: `make dev.up.lms`
- Run studio: `make dev.up.studio`
- Run ngrok: `ngrok http 18000`
- Set LTI_BASE and LTI_API_BASE on the LMS and Studio settings:
	- LTI_BASE="http://localhost:18000"
	- LTI_API_BASE="https://34a7-190-142-38-224.ngrok-free.app"
- Install xblock-lti-consumer and openedx-ltistore on the LMS and Studio.
- Add 'lti_consumer' to course advance setting 'Advanced Module List'.
- Add LTI 1.3 consumer XBlock to a course.
- Enable AGS on the LTI consumer XBlock.
- Go to the learning MFE and get the XBlock location using the "Staff Debug Info" button.
- Clone https://github.com/kuipumu/lti1p3_scripts
- Generate a key pair on IMS RI: https://lti-ri.imsglobal.org/keygen/index
- Save them as id_rsa (private key) and id_rsa.pub (public key) on the lti1p3_scripts folder.
- Go to http://localhost:18000/admin/lti_consumer/lticonfiguration/
- Replace the Lti 1p3 internal private key with the id_rsa key.
- Copy the Lti 1p3 client id and Lti 1p3 internal private key id values.
- Go to http://localhost:18000/admin/lti_store/externallticonfiguration/
- Create a new LTI external configuration using the same private key, private key id we set on the XBlock LTI configuration and generated public key.
- Copy the LTI external configuration ID.
- Create a platforms.json on lti1p3_scripts.
- Add an item for each access token endpoints:
```
{
	"xblock": {
          "client_id": "Lti 1p3 client id",
          "token_url": "http://localhost:18000/lti_store/v1/token/{lti_external_configuration_id}"
	},
	"lti_store": {
          "client_id": "Lti 1p3 client id",
          # User the XBlock access token URL.
          "token_url": "https://34a7-190-142-38-224.ngrok-free.app/api/lti_consumer/v1/token/4d0bfb92-7029-469c-98bf-db91cf022384"
	}
}
```
- Run the token_request.py script: `python3 lti1p3_scripts/token_request.py lti_store`
- Copy the generated access token.
- Go to http://localhost:18000/admin/lti_consumer/ltiagslineitem
- Copy the LTI AGS line item ID of your LTI consumer XBlock.
- Go to http://localhost:18000/admin/external_user_ids/externalid/
- Copy your external user ID.
- Open Postman and import this collection JSON: 
- Edit the "AGS Score" request URL from the LTI 1.3 collection to match your LTI AGS line item ID:
	- https://34a7-190-142-38-224.ngrok-free.app/api/lti_consumer/v1/lti/{line_item_id}/lti-ags/1/scores
- Edit the "AGS Score" request "Body" tab and change the "userId" value to your external user ID.
- Go to the "AGS Score" request "Authorization" tab and change the token value to the generated access token.
- Send the POST request.
- You should receive a 200 response with the updated score.

## Reviewers

- [ ] @Squirrel18 
- [ ] @anfbermudezme 
- [ ] @Jacatove 
- [ ] @alexjmpb

2023-06-05 19:27 UTC, kuipumu commented on lti_store/views.py
> +HTTP_404_NOT_FOUND = 404
@alexjmpb Using rest_framework.status would require adding an unnecessary dependency, I created a constant for both 400 and 404 to reuse it on the tests module, I will remove HTTP_404_NOT_FOUND since I noticed it's only use once on the tests.

2023-06-05 19:36 UTC, kuipumu commented on lti_store/key_handlers.py
> +class ToolKeyHandler:
@alexjmpb I don't think the effort is worth considering only common method is validate_and_decode, this will require modifying all the key handlers tests, I don't think any other mayor change will be made since it already complies with what the LTI 1.3 key handling spec required. We will also move back to use the access token and keyset URL on xblock-lti-consumer once the work on decoupling the LTI configuration model is done.

2023-06-05 20:35 UTC, alexjmpb approved these changes

2023-06-12 21:14 UTC, anfbermudezme requested changes

2023-06-12 21:14 UTC, anfbermudezme commented on lti_store/views.py
> +        # Scopes are space separated as described in
```suggestion
        # Scopes are space separated as described in https://tools.ietf.org/html/rfc6749
```

2023-06-13 01:15 UTC, Squirrel18 requested changes

2023-06-13 01:15 UTC, Squirrel18 commented on lti_store/key_handlers.py
> +                raise InvalidRsaKey() from err
```suggestion
                raise InvalidRsaKey()
```
Is this statement required? @kuipumu

2023-06-13 01:15 UTC, Squirrel18 commented on lti_store/key_handlers.py
> +        _message = copy.deepcopy(message)
Why are you using the underscore notation? @kuipumu

2023-06-13 01:15 UTC, Squirrel18 commented on lti_store/key_handlers.py
> +                }
Trailing comma. @kuipumu

2023-06-13 01:15 UTC, Squirrel18 commented on lti_store/key_handlers.py
> +                        "not match the expected iss value."
Trailing comma. @kuipumu

2023-06-13 01:15 UTC, Squirrel18 commented on lti_store/key_handlers.py
> +    def validate_and_decode(self, token, iss=None, aud=None):
Please, be consistent with the return statements. @kuipumu

2023-06-13 01:15 UTC, Squirrel18 commented on lti_store/urls.py
> +        "v1/token/<int:lti_config_id>",
Why has a "V1" API been created, is there a V0? @kuipumu

2023-06-13 01:15 UTC, Squirrel18 commented on lti_store/views.py
> +HTTP_400_BAD_REQUEST = 400
There is no need to define this, you can use: https://docs.djangoproject.com/en/4.2/ref/request-response/#django.http.HttpResponseNotFound or https://www.django-rest-framework.org/api-guide/status-codes/#client-error-4xx

2023-06-14 03:16 UTC, kuipumu commented on lti_store/key_handlers.py
> +        # Import from public key
It was to describe that the key string was being loaded into a instance attribute, but its unnecessary since this is already being commented bellow.

2023-06-14 03:26 UTC, kuipumu commented on lti_store/key_handlers.py
> +                token, keys=self._get_keyset(jwt.headers.get("kid"))
@anfbermudezme I cannot change get("kid") since that's where the JWT headers stores the kid, or do you meant replacing kid on some other line?

2023-06-14 03:34 UTC, kuipumu commented on lti_store/key_handlers.py
> +            key_pem (str): Key PEM.
PEM is a format to store cryptographic keys, in this case a RSA private key: http://fileformats.archiveteam.org/wiki/PEM

2023-06-14 03:38 UTC, kuipumu commented on lti_store/key_handlers.py
> +        # Set iat and exp if expiration is set.
According to the JSON Web Token specification RFC 7519:

"The "iat" (issued at) claim identifies the time at which the JWT was issued."
"The "exp" (expiration time) claim identifies the expiration time on or after which the JWT MUST NOT be accepted for processing."

https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6
https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4

2023-06-14 04:07 UTC, kuipumu commented on lti_store/key_handlers.py
> +    def validate_and_decode(self, token):
@Squirrel18 Do you mean validate_and_decode method or _get_keyset?, I see both having a return statement

2023-06-14 04:12 UTC, kuipumu commented on lti_store/key_handlers.py
> +                raise InvalidRsaKey() from err
It's not required but makes the exception chain explicit, should I also make it implicit on all other exceptions?

2023-06-14 04:15 UTC, kuipumu commented on lti_store/key_handlers.py
> +        _message = copy.deepcopy(message)
@Squirrel18 So I could keep using the same variable name on the object copy, do you think we should use a different variable name?

2023-06-14 04:24 UTC, kuipumu commented on lti_store/views.py
> +HTTP_400_BAD_REQUEST = 400
@Squirrel18 Django rest framework it's not a dependency of openedx-ltistore and HttpResponseNotFound doesn't work like JsonResponse

2023-06-14 04:30 UTC, kuipumu commented on lti_store/key_handlers.py
> +    def validate_and_decode(self, token, iss=None, aud=None):
@Squirrel18 Same comment as before, do you mean validate_and_decode or get_public_jwk?, I only see validate_and_decode either returning the message or raising an exception

2023-06-14 04:40 UTC, kuipumu commented on lti_store/key_handlers.py
> +                        "not match the expected iss value."
@Squirrel18 I cannot add a line break since will make the __init__ method recognize a 3rd parameter.

2023-06-15 13:52 UTC, anfbermudezme commented
What do you think add a github actions to validate Pylint and the tests related?

2023-06-15 17:52 UTC, anfbermudezme approved these changes

2023-06-21 02:59 UTC, Squirrel18 requested changes

2023-06-21 02:59 UTC, Squirrel18 commented on lti_store/key_handlers.py
> +        _message = copy.deepcopy(message)
Well, that depends on the purpose... I think that the underscore notation is confusing in Python and I always try to avoid it. Perhaps changing the variable name is OK. @kuipumu

2023-06-21 02:59 UTC, Squirrel18 commented on lti_store/key_handlers.py
> +        _jws = JWS(_message, alg="RS256", cty="JWT")
Same comment as above. @kuipumu

2023-06-21 02:59 UTC, Squirrel18 commented on lti_store/key_handlers.py
> +        return json.loads(public_keys.dump_jwks())
What is the point of returning even if there is no key? @kuipumu

2023-06-21 02:59 UTC, Squirrel18 commented on lti_store/key_handlers.py
> +                raise InvalidClaimValue(
You should use the message attribute instead of defining a custom message. @kuipumu

2023-06-21 02:59 UTC, Squirrel18 commented on lti_store/views.py
> +@xframe_options_sameorigin
Why do you need to add this? @kuipumu

2023-06-21 02:59 UTC, Squirrel18 commented on lti_store/views.py
> +        return JsonResponse(
Is it worth creating a serializer for this response? @kuipumu

2023-06-21 04:53 UTC, kuipumu commented on lti_store/key_handlers.py
> +    def validate_and_decode(self, token):
@Squirrel18 Adding another return statement at the end of this method doesn't make sense since it will never be reached

2023-06-21 05:19 UTC, kuipumu commented on lti_store/key_handlers.py
> +                raise InvalidClaimValue(
@Squirrel18 The exception message is used on the logs when there is no message added to the exception, in this case we override the message to be more specific about the invalid claim, what do you think about keeping these messages instead of using the exception default message attribute?

2023-06-21 05:23 UTC, kuipumu commented on lti_store/views.py
> +@xframe_options_sameorigin
@Squirrel18 This is to make sure that the X-Frame-Options HTTP header is set to 'SAMEORIGIN' even if the Django middleware is setting it to 'DENY', there might be cases on which we might need the access token available from an iframe

2023-06-21 05:24 UTC, kuipumu commented on lti_store/views.py
> +        return JsonResponse(
@Squirrel18 I don't think so, I think that will add an unnecessary complexity just for this view output

2023-06-23 05:29 UTC, Squirrel18 requested changes

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_key_handlers.py
> +    def test_encode_and_sign(self):
Please, check that deepcopy, JWS and sign_compact have been called. @kuipumu

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_key_handlers.py
> +        self.assertEqual(self._decode_token(signed_token), message)
```suggestion
        message = {"test": "test"}
        
        signed_token = self.key_handler.encode_and_sign(message)
        
        self.assertEqual(self._decode_token(signed_token), message)
```

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_key_handlers.py
> +    def test_empty_rsa_key(self):
In case the key_pem is empty, shouldn't InvalidRsaKey be raised? @kuipumu

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_key_handlers.py
> +    def test_validate_and_decode(self, mock_time):
Is it necessary to check that verify_compact has been called? @kuipumu

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_key_handlers.py
> +        self._setup_key_handler()
Why didn't you just call: ToolKeyHandler(public_key=self.public_key)? @kuipumu

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_key_handlers.py
> +    def test_get_keyset_with_pub_key(self):
Please, check that load_jwks_from_url has been called. @kuipumu 
Also, check non-happy path cases.

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_key_handlers.py
> +    def test_validate_and_decode(self, mock_time):
Please, check that unpack, verify_compact and _get_keyset have been called. @kuipumu

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_key_handlers.py
> +    def test_validate_and_decode_bad_signature(self, mock_verify_compact):
Missing test case for MalformedJwtToken. @kuipumu

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_views.py
> +CONTENT_TYPE = "application/x-www-form-urlencoded"
```suggestion
CONFIG_ID = 1
CLIENT_ID = "test-client-id"
PUBLIC_KEY = "test-public-key"
KEYSET_URL = "test-keyset-url"
PRIVATE_KEY = "test-private-key"
PRIVATE_KEY_ID = "test-private-key-id"
API_BASE = "test-lti-base"
JWT_TOKEN = "test-jwt-token"
ACCESS_TOKEN = "test-access-token"
EXPIRATION = 3600
SCOPES = [
    "https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly",
    "https://purl.imsglobal.org/spec/lti-ags/scope/lineitem",
    "https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly",
    "https://purl.imsglobal.org/spec/lti-ags/scope/score",
    "https://purl.imsglobal.org/spec/lti-nrps/scope/contextmembership.readonly",
]
SCOPE_STR = " ".join(SCOPES)
CONTENT_TYPE = "application/x-www-form-urlencoded"
```

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_views.py
> +    def test_access_token_request(
Check that urllib.parse.parse_qsl has been called. @kuipumu

2023-06-23 05:29 UTC, Squirrel18 commented on lti_store/tests/test_views.py
> +class TestAccessTokenEndpointView(TestCase):
Missing test case for UnsupportedGrantType. @kuipumu

2023-06-23 16:55 UTC, kuipumu commented on lti_store/tests/test_key_handlers.py
> +    def test_empty_rsa_key(self):
@Squirrel18 InvalidRsaKey is not raised because self.key is never tried to be imported because the key_pem argument is empty, instead RsaKeyNotSet is raised by encode_and_sign while evaluatig if self.key is set

2023-06-23 20:25 UTC, kuipumu commented on lti_store/tests/test_views.py
> +class TestAccessTokenEndpointView(TestCase):
@Squirrel18 There is already a test case for UnsupportedGrantType called test_unsupported_grant_type on TestAccessTokenEndpointView

2023-06-27 16:47 UTC, Squirrel18 approved these changes

2023-06-27 17:55 UTC, merged