PADV-504: Implement LTI 1.3 reusable configuration
Pearson-Advance/openedx-ltistore pull request #4
Opened 2023-06-27 18:49 UTC by kuipumu

## Ticket

https://agile-jira.pearson.com/browse/PADV-504

## Description

This PR adds compatibility for LTI 1.3 external configuration to the openedx-ltistore. This change adds missing fields required for LTI 1.3 external reusable configurations to work, also adds the lti_1p3_access_token_url and lti_1p3_keyset_url properties to the ExternalLtiConfiguration and the lti_1p3_access_token_url and lti_1p3_keyset_url values to the GetLtiConfigurations pipeline, these are required for the LTI consumer XBlock to show the correct keyset and access token URL to the course author.

- [x] Add lti_1p3_deployment_id, lti_1p3_oidc_url, lti_1p3_launch_url fields to ExternalLtiConfiguration model.
- [x] Add lti_1p3_access_token_url and lti_1p3_keyset_url properties to ExternalLtiConfiguration model.
- [x] Add lti_1p3_access_token_url and lti_1p3_keyset_url values to GetLtiConfigurations pipeline.
- [x] Improve ExternalLtiConfiguration LTI 1.3 fields descriptions.
- [x] Include unit tests for all added and modified code.

## Testing

1. Install and configure xblock-lti-consumer
2. Install and configure openedx-ltistore (follow the setup steps from: https://github.com/openedx/xblock-lti-consumer/pull/239)
3. Create an IMS reference tool: https://lti-ri.imsglobal.org/lti/tools
4. Go to http://localhost:18000/admin/lti_store/externallticonfiguration/ and create a new external LTI 1.3 configuration.
5. Fill the "LTI 1.3 Private Key",  "LTI 1.3 Client ID" and "LTI 1.3 Tool Keyset URL" or "LTI 1.3 Tool Public Key" field.
6. Create a course and add a LTI 1.3 consumer XBlock.
7. Set the consumer XBlock to user an external configuration and set the reusable configuration ID (follow the steps on how to get the filter key from: https://github.com/openedx/xblock-lti-consumer/pull/239) 
8. Copy the keyset and access token URL from the XBlock preview back to the IMS reference tool previously created. 
9. Go to the course a launch the XBlock.
10. The LTI 1.3 launch should be valid.
11. Repeat the test while changing the deployment ID on the external LTI configuration and IMS reference tool.
12. Repeat the test setting the OIDC and launch URL on the XBlock and check if the values from the XBlock are being used instead of the values on the external configuration.
13. Check that the XBlock doesn't allow you to set the external configuration type without adding an external configuration ID.

## Reviewers

- [ ] @squirrel18
- [ ] @alexjmpb
- [ ] @anfbermudezme

2023-07-04 16:46 UTC, anfbermudezme requested changes

2023-07-04 16:46 UTC, anfbermudezme commented on lti_store/models.py
> +        help_text="This is the LTI launch URL, otherwise known as the target_link_uri. "
What is the meaning of `..link_uri`?

2023-07-04 16:46 UTC, anfbermudezme commented on lti_store/models.py
> +            get_lti_api_base(), f"/{LtiStoreConfig.name}/token/{self.pk}"
```suggestion
            get_lti_api_base(),
            f"/{LtiStoreConfig.name}/token/{self.pk}",
```

2023-07-04 16:46 UTC, anfbermudezme commented on lti_store/models.py
> +            get_lti_api_base(), f"/{LtiStoreConfig.name}/public_keyset/{self.pk}"
```suggestion
            get_lti_api_base(),
            f"/{LtiStoreConfig.name}/public_keyset/{self.pk}",
```

2023-07-04 23:50 UTC, kuipumu commented on lti_store/models.py
> +    lti_1p3_oidc_url = models.CharField(
@anfbermudezme It's an abbreviation of OpenID Connect, this is the URL used by the platform to authenticate authentication with the tool on launch.

2023-07-04 23:52 UTC, kuipumu commented on lti_store/models.py
> +        help_text="This is the LTI launch URL, otherwise known as the target_link_uri. "
This is how the launch URL is also called on the LTI 1.3 spec: https://www.imsglobal.org/node/162741#target-link-uri

2023-07-07 00:20 UTC, alexjmpb approved these changes

2023-07-07 21:42 UTC, Squirrel18 requested changes

2023-07-07 21:42 UTC, Squirrel18 commented on lti_store/models.py
> +        help_text="This is the OIDC third-party initiated login endpoint URL in the LTI 1.3 flow, "
Please, user multi-line comments. @kuipumu

2023-07-07 21:42 UTC, Squirrel18 commented on lti_store/models.py
> +        help_text="This is the LTI launch URL, otherwise known as the target_link_uri. "
```suggestion
        help_text="This is the LTI launch URL, otherwise known as the target_link_uri."
```
Please, use multi-line comments, @kuipumu

2023-07-07 21:42 UTC, Squirrel18 commented on lti_store/pipelines.py
> +                for c in config_objs
```suggestion
                for config_obj in config_objs
```

2023-07-07 21:42 UTC, Squirrel18 commented on lti_store/tests/test_pipelines.py
> +    def test_filter_returns_all_the_available_configs_when_config_id_is_not_set(
Please, add some assertions for lti_1p3_keyset_url and lti_1p3_access_token_url. @kuipumu

2023-07-07 22:21 UTC, Squirrel18 approved these changes

2023-07-07 23:31 UTC, merged